import type { NextPage } from "next";
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillLinkedin, AiFillInstagram, AiFillGithub } from "react-icons/ai";
import Image from "next/image";
import scratching from "../public/bitmoji-scratching.png";
import fountain from "../public/bitmoji-water-fountain.png";
import show from "../public/bitmoji-show.png";
import working from "../public/bitmoji-portfolio.png";
import chart from "../public/bitmoji-retail-chart.png";
import dark from "../public/bitmoji-dark.png";
import { useState } from "react";

type contactMeFormType = {
  firstName: string;
  lastName: string;
  email: string;
};
const Home: NextPage = () => {
  const [darkMode, setDarkMode] = useState(false);
  const [contactMeFormData, setContactMeFormData] =
    useState<contactMeFormType>();
  const onSubmit = () => {};
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Yassine CHAFIK</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="flex justify-between py-10">
            <h1 className="font-burtons text-xl dark:text-gray-400">
              ychafik.com
            </h1>
            <ul className="flex items-center gap-5">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl dark:text-white"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
            </ul>
          </nav>
          <div className="p-10 text-center">
            <h2 className="py-2 text-5xl font-medium text-teal-600 md:text-6xl">
              Yassine CHAFIK
            </h2>
            <h3 className="py-2 text-2xl dark:text-gray-400 md:text-3xl">
              Full Stack Developer based in Paris
            </h3>
            <p className="text-md mx-auto max-w-lg  py-5 leading-8 text-gray-800 dark:text-gray-400 md:text-xl">
              One day i was born, since then I improvise...
            </p>
          </div>
          <div className="relative mx-auto mt-20 h-80 w-80 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 md:h-96 md:w-96">
            <Image
              src={darkMode ? dark : scratching}
              alt="Yassine CHAFIK Avatar"
              layout="fill"
              objectFit="cover"
            />
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="py-1 text-3xl dark:text-gray-400">
              Services I offer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-400">
              Since 2018, I took a great pleasure working on business
              applications in the{" "}
              <span className="text-teal-500">HR industrie</span>. I have helped
              my company find the best freelancers and consultants for big
              clients like banks or energy providers.
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-400">
              Today i can help your team or your business improve their system
              or visibility.
            </p>
          </div>
          <div className="gap-10 dark:text-gray-400 lg:flex">
            <div className="rounded-xl p-10 text-center shadow-lg">
              <Image
                className="w-200 h-200"
                src={fountain}
                alt="Yassine CHAFIK water fountain"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium">
                Logistic applications
              </h3>
              <p>
                Your team is struggling to keep up with their excel files? What
                if you and I work together to automate all the boring stuff your
                team is dealing with so you can finaly focus on the interesting
                part of your work?
              </p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className="py-1 text-gray-800 dark:text-gray-200">
                JavaScript/TypeScript
              </p>
              <p className="py-1 text-gray-800 dark:text-gray-200">AWS/GCP</p>
              <p className="py-1 text-gray-800 dark:text-gray-200">
                MongoDB/ElasticSearch
              </p>
            </div>
            <div className="rounded-xl p-10 text-center shadow-lg">
              <Image
                className="w-200 h-200"
                src={show}
                alt="Yassine CHAFIK showcase"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium">
                Showcase website
              </h3>
              <p>
                Your business needs a better visibility and you have no idea
                what SEO is? I got you covered. We will work on making sure the
                internet knows what you have to offer.
              </p>
              <h4 className="py-4 text-teal-600">Tools</h4>
              <p className="py-1 text-gray-800 dark:text-gray-200">
                Google Analytics
              </p>
              <p className="py-1 text-gray-800 dark:text-gray-200">
                Responsive design
              </p>
              <p className="py-1 text-gray-800 dark:text-gray-200 ">html/css</p>
            </div>
            <div className="rounded-xl p-10 text-center shadow-lg">
              <Image
                className="w-200 h-200"
                src={chart}
                alt="Yassine CHAFIK water chart"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium">
                Retail interface
              </h3>
              <p>
                You have stuffs to sell and you need a friendly way for your
                customers to pay online? I can provide you a safe solution to
                manage your sales.
              </p>
              <h4 className="py-4 text-teal-600 ">Tools</h4>
              <p className="py-1 text-gray-800  dark:text-gray-200 ">
                Google Pay
              </p>
              <p className="py-1 text-gray-800  dark:text-gray-200 ">Stripe</p>
              <p className="py-1 text-gray-800  dark:text-gray-200 ">Paypal</p>
            </div>
          </div>
        </section>
        <section>
          <div className="mb-20 md:mb-20">
            <h3 className="py-1 text-3xl dark:text-gray-400">Portfolio</h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-400">
              This section is currently in developement. Come back later to see
              what I have been working on!
            </p>
            <div className="mx-auto max-w-xs">
              <Image
                className="w-100 h-100"
                src={working}
                alt="Yassine CHAFIK working"
              />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="py-1 text-3xl dark:text-gray-400">Contact me</h3>
            <form onSubmit={onSubmit}>
              <div className="mx-auto flex max-w-lg flex-col gap-5 py-10">
                <div className="flex">
                  <span className="inline-flex items-center rounded-l-md border border-r-0 border-gray-300 bg-gray-200 px-3 text-sm text-gray-900 dark:border-gray-600 dark:bg-gray-600 dark:text-gray-400">
                    @
                  </span>
                  <input
                    type="text"
                    id="website-admin"
                    className="dark:focus:ring-teal-500v block w-full min-w-0 flex-1 rounded-none rounded-r-lg border border-gray-300 bg-gray-50 p-2.5 text-sm text-gray-900 focus:border-teal-500  focus:ring-teal-500 dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-teal-500"
                    placeholder="your name"
                  />
                </div>
                <div className="relative mb-6">
                  <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                    <svg
                      aria-hidden="true"
                      className="h-5 w-5 text-gray-500 dark:text-gray-400"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path d="M2.003 5.884L10 9.882l7.997-3.998A2 2 0 0016 4H4a2 2 0 00-1.997 1.884z"></path>
                      <path d="M18 8.118l-8 4-8-4V14a2 2 0 002 2h12a2 2 0 002-2V8.118z"></path>
                    </svg>
                  </div>
                  <input
                    type="text"
                    id="input-group-1"
                    className="block w-full rounded-lg border border-gray-300 bg-gray-50 p-2.5 pl-10 text-sm text-gray-900 focus:border-teal-500 focus:ring-teal-500  dark:border-gray-600 dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 dark:focus:border-teal-500 dark:focus:ring-teal-500"
                    placeholder="your email"
                  />
                </div>

                <button
                  className="rounded-md border-none bg-gradient-to-r from-cyan-500 to-teal-500 px-4 py-2 text-white"
                  type="submit"
                >
                  Send
                </button>
              </div>
            </form>
          </div>
        </section>
        <section>
          <div className="h flex justify-center gap-16 py-10 text-5xl text-gray-600 dark:text-gray-400">
            <a href="https://www.linkedin.com/in/yassine-chafik/">
              <AiFillLinkedin />
            </a>
            <a href="https://www.instagram.com/ya2s_la_menace/">
              <AiFillInstagram />
            </a>
            <a href="https://github.com/YChafik">
              <AiFillGithub />
            </a>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
